export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";

export const FETCH_COMMANDES = "FETCH_COMMANDES";
export const FETCH_COMMANDES_SUCCESS = "FETCH_COMMANDES_SUCCESS";
export const FETCH_COMMANDES_FAIL = "FETCH_COMMANDES_FAIL";

export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"

export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"

export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"

export const REGISTER_USER = `REGISTER_USER`;
export const REGISTER_SUCCESS = `REGISTER_SUCCESS`;
export const REGISTER_FAIL = `REGISTER_FAIL`;

export const GET_PROFILE = `GET_PROFILE`;
export const GET_PROFILE_SUCCESS = `GET_PROFILE_SUCCESS`;
export const GET_PROFILE_FAIL = `GET_PROFILE_FAIL`;

export const RATE_SUCCESS = "RATE_SUCCESS"
export const RATE_FAIL  = "RATE_FAIL"

export const LOGIN_USER = `LOGIN_USER`;
export const LOGIN_SUCCESS = `LOGIN_SUCCESS`;
export const LOGIN_FAIL = `LOGIN_FAIL`;

export const ADD_COMMANDE = 'ADD_COMMANDE'
export const ADD_COMMANDE_SUCCESS = 'ADD_COMMANDE_SUCCESS'
export const ADD_COMMANDE_FAIL = 'ADD_COMMANDE_FAIL'

export const USER_TOTAL = 'USER_TOTAL'
export const USER_TOTAL_SUCCESS = 'USER_TOTAL_SUCCESS'
export const USER_TOTAL_FAIL = 'USER_TOTAL_FAIL'


export const LOG_OUT = "LOG_OUT";

export const GET_TOTAL = 'GET_TOTAL'

export const ADD_TO_CART = "ADD_TO_CART";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

export const INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";

export const SEARCH = "SEARCH"
